name: Deploy Spring Boot API

env:
  DB_URL: ${{ secrets.DB_URL }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASSWORD }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Puedes usar 'zulu' o 'adopt' si prefieres otra distribución
        java-version: '21'

    - name: Check Java version
      run: java -version
  
    - name: Build JAR
      run: ./gradlew build # o mvn package si usas Maven

    - name: Check Java version
      run: java -version

    - name: Rename JAR
      run: |
        mkdir -p build/libs/final
        cp build/libs/*.jar build/libs/final/app.jar

    - name: Copy JAR to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: build/libs/final/app.jar
        target: /opt/spring-auth-api/

    - name: Restart Spring Boot service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        envs: DB_URL,DB_USER,DB_PASSWORD
        script: |
          echo "Usando DB_URL=$DB_URL"
          export DB_URL=$DB_URL
          export DB_USER=$DB_USER
          export DB_PASS=$DB_PASSWORD
          sudo systemctl restart spring-auth-api.service

